package com.nitnem.tracker.model;

public enum UserState {

    IDLE,

    WAITING_FOR_CREATE_NITNEM_NAME,
    WAITING_FOR_CREATE_NITNEM_UNIT,

    WAITING_FOR_CREATE_TOTAL_COUNT,

    WAITING_FOR_CREATE_DURATION_DAYS,

    WAITING_FOR_UPDATE_NITNEM_NAME,
    WAITING_FOR_UPDATE_NITNEM_UNIT,

    WAITING_FOR_UPDATE_NITNEM_COUNT,

    WAITING_FOR_DELETE_NITNEM_NAME
}