name: Health Check

on:
  workflow_dispatch:

#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Check Health Nitnem Tracker
        run: curl https://nitnem-tracker.onrender.com/